[versions]
androidGradle = "7.0.2"
kotlin = "1.5.30"
pluginPublish = "0.15.0"
metalavaGradle = "0.1.9"

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
metalavaGradle = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalavaGradle" }

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
